# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57c4d6bd4b14d2a091ee0babb8e65f182a1da3d975ee827b0310f8e81d0b149d460589b010c1bd38a0dd6b047ac5f8046e896f30e39b61a27d6146c0cb83ea73

test:
  secret_key_base: 70e368b5465dd26b07513a99d5043f2cdb64ef13ca710bfa5f87712960c3cfb0f6abc028030335122125e172ecdb3fe4b3a7354ac352f30c0c9cab48b44a48ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
